### ISSUE TITLE
JWT 토큰 페이로드에 user_id 추가 요청

### ISSUE THREAD

**Issue by axisotherwise** [Broccoli-Velog/Broccoli-Backend#10]
## 요구/개선 기능

토큰 페이로드 user_id 추가 요청

### 자세히
현재 페이로드에 nickname만 전달하는데 nickname을 통해 사용자를 찾을 수 있지만 불필요한 과정이므로 comment 테이블의  외래 키가 user 테이블의 user_id므로 댓글 기능 사용 시 사용자 아이디(user_id)가 필요합니다.

**Comment by unchaptered** [comment]
JWT 토큰을 디코딩하면, 페이로드에 userId 와 nickname 이 존재합니다.
