### ISSUE TITLE
Backend - token이슈, Unauthorized

### ISSUE THREAD

**Issue by dusunax** [Broccoli-Velog/Broccoli-Backend#27]
## 토큰을 사용해서 POST Note

1. 예상행동: 
Local Storage에 저장된 토큰을 헤더에 넣어서 POST, 
새로운 노트 추가하기

```jsx
const options2 = {
  url: 'http://localhost:3000/note',
  method: 'post',
  header: { Authorization : `${localStorage.getItem('broccolis')}`},
  data: {
    'title': '제목 1',
    'context': '내용 1'
  }
}
axios(options2)
.then(res=>{
  console.log(res.data.result.queryResult)
})
.catch(err=>{
  console.log(err.response.data);
})
.finally(() => console.log('axios 실행'))
```
2. 에러메시지, unauthorized:
- message: 'token 이 누락되었습니다.'
 ![image](https://user-images.githubusercontent.com/94776135/182792393-73752fbf-dec1-4ae2-98a0-45285bf0d477.png)

- 저장된 토큰
 ![image](https://user-images.githubusercontent.com/94776135/182791739-019eabcb-78a5-4642-9622-0c3f6c7d836c.png)

**Comment by dusunax** [comment]
- 코드 다른 방식으로 짜봄
```jsx
axios.post(url, data, {
  headers: {
    'Authorization': `Basic ${localStorage.getItem('broccolis')}`
  },
}).then(res=>{
  console.log(res.data.result.queryResult)
})
.catch(err=>{
  console.log(err.response.data);
})
.finally(() => console.log('axios 실행'))
```
- 401 에러
![image](https://user-images.githubusercontent.com/94776135/182855485-6e54c9ae-de7d-482c-b3f1-357b1a0940af.png)

---

- token 이름 바꿔서 새로 받아봄 => 같은 오류
- 지금 작동되는 거: login, register, GET note

**Comment by unchaptered** [comment]
현재 백엔드 서버에서는 `Bearer Authentication` 을 사용하고 있습니다.
따라서, `Bearer ${Token}` 방식으로 req.hearders.authorization 항목에 넣어주시면 에러가 해결되지 않을까 싶습니다.

**Comment by dusunax** [comment]
- Bearer ${Token}으로 같은 에러 뜹니다.

![image](https://user-images.githubusercontent.com/94776135/183070620-f6c87a20-6c6d-4311-a806-559bbd139769.png)
```jsx
axios.post('http://localhost:3000/note', 
    { headers: {
        'Authorization': `Bearer ${localStorage.getItem('test2')}`
    },
        'title': '제목 1',
        'context': '내용 1'
    }
).then(res=>{
    console.log(res.data.result.queryResult)
})
.catch(err=>{
    console.log(err.response.data);
})
.finally(() => console.log('axios 실행'))
```

---
1. 헤더에 Authorization, authorization, 'Authorization', 'authorization', Bearer, bearer 체크해봄
2. token을 변수에 넣어서 사용해봄
```jsx
{ headers: {
    authorization: `Bearer ${token}`
},
    'title': '제목 1',
    'context': '내용 1'
}
```

**Comment by dusunax** [comment]
- headers의 위치 오류 수정!
```jsx
axios.post('http://localhost:3000/note', {
    "title": "dfdfwefee",
    "content": "sdfdsfsdf"
}, {
    headers: {
        authorization: `Bearer ${localStorage.getItem('token')}`
    }
}).then(res => {
    console.log(res.data.result.queryResult)
})
.catch(err => {
    console.log(err.response.data);
})
.finally(() => console.log('axios 실행'))
```

**Comment by unchaptered** [comment]
프론트 앤드에서 서버 API 호출 간에 문제가 생기면, 발생 지점을 찾아내기가 힘들다는 점이 있었습니다.
문제 지점이 발생되면, console 을 통해서 찾아야 하는데 해당 처리가 미흡하게 되어 있는 것 같습니다.

최고의 해결 방법은 morgan 이 아니라 winston 을 사용해서 로그를 좋게 남기거나, 아니면 `error/20220805` 브런치를 임시로 만들어서 백앤드 단에서 직접 수정을 하면서 체킹하는 방법이 있을 것 같습니다.

### 솔루션

1. 로깅을 더 꼼꼼하게
2. 빠른 소통?

**Comment by unchaptered** [comment]
> * Bearer ${Token}으로 같은 에러 뜹니다.
>  ... more

axios 는 get 메서드를 제외하고 URL, body, options 로 구성되어 있었던 것을 확인했습니다.
